### ISSUE TITLE
Installera Unity version: 2017.4.0f1

### ISSUE THREAD

**Issue by Jarvitalo** [Jarvitalo/mapp2#5]

**Comment by Lornelin** [comment]
Ska vi dubbelkolla att det är exakt den versionen i skolan? Den släpptes 20:e mars så måste ha installerats precis efter det isf.
Finns även en 2017.4.1f1 nu, men den släpptes i fredags så den lär det inte vara om de inte uppdaterat i helgen.

**Comment by NorthernFoxFire** [comment]
Jag har laddat ned nu
